version: '3.8'
services:
  # These are the configurations for our Node app
  # When Docker Compose starts this container it will automatically
  # use the Dockerfile in the directory to configure it
  backend:
    build: ./
    ports:
      - "3000:3000"
    volumes:
      # Maps our current project directory `.` to
      # our working directory in the container
      - ./:/usr/src/app/
      # node_modules workaround for volumes
      # https://stackoverflow.com/a/32785014
      - /usr/src/app/node_modules
  island-generator:
    build: ../island-generator
    ports:
      - "8080:8080"
    volumes:
      - '../island-generator:/usr/src/app'
      - '/usr/src/app/node_modules'
  frontend:
    # container_name: memory-islands-frontend
    build: ../frontend
    volumes:
      - '../frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - "3333:3333"
    environment:
      - CHOKIDAR_USEPOLLING=true

